[project]
name = "lehmer"
dynamic = ['version']
description = "A minimal, vectorized and batchable library for computing Lehmer codes."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
keywords = [
    "lehmer",
    "Lehmer",
    "Lehmer codes",
    "permutations",
    "combinatorics",
    "factoradic",
    "batchable",
    "vectorized",
    "numpy",
    "rubik's cube"
]
authors = [{ name = "Diego Sandoval", email = "dsandovalv@gmail.com" }]
maintainers = [{ name = "Diego Sandoval", email = "dsandovalv@gmail.com" }]

dependencies = ["numpy>=2.2.0"]

[project.optional-dependencies]
dev = ["pre-commit", "hatch", "ruff"]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"


[project.urls]
Homepage = "https://github.com/twaclaw/lehmer"
Documentation = "https://github.com/twaclaw/lehmer"
Issues = "https://github.com/twaclaw/lehmer/issues"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["src/lehmer"]


[tool.hatch.build.targets.sdist]
include = ["src/lehmer", "README.md"]

[tool.hatch.envs.default]
installer = "uv"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]

[tool.hatch.envs.hatch-test]
dependencies = ["pytest", "pytest-cov"]
dev-mode = true

[tool.ruff]
line-length = 179
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "I", "T201"]
ignore = ["F722"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
